language: node_js
node_js:
- 0.1
notifications:
  slack:
    secure: aQEFj8k4JKdmflWLutqsiABdHjYtxNHFw37eUz3EYqIHGvsue88MsuD1NEjAJNumBfSojcsREZN7IauXv6E/o3hzb/23Ng/kGXMA4J/Lrs1fLG5o8JFtvobQFb8euVT1pZhLeUH1ux97Xsf5InltyIH3gcRVvuchfLUyE+oyEeU=
