language: node_js
node_js:
  - 0.10


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b4d58c9d51c993a7dd45
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
